import { DeFiAgent, Strategy } from './types';

export const mockAgents: DeFiAgent[] = [
  {
    fid: 1001,
    basename: 'yieldmaster.base.eth',
    displayName: 'Yield Master',
    pfpUrl: 'https://i.imgur.com/placeholder1.png',
    performanceMetrics: {
      totalReturn: 47.3,
      winRate: 78,
      avgAPY: 23.5,
      strategiesCreated: 12,
    },
    solanaPortfolioValue: 125000,
    basePortfolioValue: 230000,
    earnings: 45000,
    rating: 4.8,
    followers: 1247,
    isFollowing: false,
  },
  {
    fid: 1002,
    basename: 'arbitragepro.base.eth',
    displayName: 'Arbitrage Pro',
    pfpUrl: 'https://i.imgur.com/placeholder2.png',
    performanceMetrics: {
      totalReturn: 62.1,
      winRate: 85,
      avgAPY: 31.2,
      strategiesCreated: 8,
    },
    solanaPortfolioValue: 89000,
    basePortfolioValue: 156000,
    earnings: 38000,
    rating: 4.9,
    followers: 2103,
    isFollowing: false,
  },
  {
    fid: 1003,
    basename: 'defiwhale.base.eth',
    displayName: 'DeFi Whale',
    pfpUrl: 'https://i.imgur.com/placeholder3.png',
    performanceMetrics: {
      totalReturn: 38.7,
      winRate: 72,
      avgAPY: 19.4,
      strategiesCreated: 15,
    },
    solanaPortfolioValue: 340000,
    basePortfolioValue: 520000,
    earnings: 92000,
    rating: 4.7,
    followers: 3456,
    isFollowing: true,
  },
];

export const mockStrategies: Strategy[] = [
  {
    strategyID: 'strat-001',
    name: 'Cross-Chain USDC Arbitrage',
    description: 'Exploit price differences of USDC between Base and Solana DEXs for consistent low-risk returns.',
    targetChain: 'Both',
    protocolIntegrations: ['Uniswap', 'Raydium', 'Wormhole'],
    riskScore: 2,
    currentAPY: 18.5,
    historicalPerformance: 15.2,
    creatorFID: 1002,
    creatorName: 'Arbitrage Pro',
    creatorAvatar: 'https://i.imgur.com/placeholder2.png',
    tvl: 2400000,
    executionCount: 847,
  },
  {
    strategyID: 'strat-002',
    name: 'Base Yield Farming Optimizer',
    description: 'Automatically rebalance between top Base yield farms to maximize APY while managing risk.',
    targetChain: 'Base',
    protocolIntegrations: ['Aave', 'Compound', 'Aerodrome'],
    riskScore: 3,
    currentAPY: 24.3,
    historicalPerformance: 21.8,
    creatorFID: 1001,
    creatorName: 'Yield Master',
    creatorAvatar: 'https://i.imgur.com/placeholder1.png',
    tvl: 5600000,
    executionCount: 1523,
  },
  {
    strategyID: 'strat-003',
    name: 'Solana Liquid Staking Plus',
    description: 'Stake SOL with top validators and deploy rewards into high-yield Solana DeFi protocols.',
    targetChain: 'Solana',
    protocolIntegrations: ['Marinade', 'Kamino', 'Drift'],
    riskScore: 4,
    currentAPY: 28.7,
    historicalPerformance: 26.3,
    creatorFID: 1003,
    creatorName: 'DeFi Whale',
    creatorAvatar: 'https://i.imgur.com/placeholder3.png',
    tvl: 8900000,
    executionCount: 2341,
  },
  {
    strategyID: 'strat-004',
    name: 'Multi-Chain Stablecoin Yield',
    description: 'Diversified stablecoin strategy across Base and Solana lending protocols for stable returns.',
    targetChain: 'Both',
    protocolIntegrations: ['Aave', 'Compound', 'Solend', 'Marginfi'],
    riskScore: 1,
    currentAPY: 12.4,
    historicalPerformance: 11.8,
    creatorFID: 1001,
    creatorName: 'Yield Master',
    creatorAvatar: 'https://i.imgur.com/placeholder1.png',
    tvl: 12000000,
    executionCount: 4567,
  },
];
